name: build-on-release
push:
  tags:
    - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: 'yarn'
      - run: yarn install --frozen-lock-file
      - run: yarn run build:widget:prod
      - run: rm -rf build
      - name: Commit new build
        run: |
          git config --global user.name 'Ehsan sarshar'
          git config --global user.email 'TheEhsanSarshar@users.noreply.github.com'
          git commit -am "new build"
          git push
